'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.296.
'
Namespace SaveJournal
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="JournalSoap", [Namespace]:="http://fldevez.org/")>  _
    Partial Public Class Journal
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private SaveJournalOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SaveJournalXMLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.clsDataModule.My.MySettings.Default.clsDataModule_SaveJournal_Journal
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event SaveJournalCompleted As SaveJournalCompletedEventHandler
        
        '''<remarks/>
        Public Event SaveJournalXMLCompleted As SaveJournalXMLCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://fldevez.org/SaveJournal", RequestNamespace:="http://fldevez.org/", ResponseNamespace:="http://fldevez.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SaveJournal(ByVal customerID As Integer, ByVal journalDate As Date, ByVal block_ID As String, ByVal transactionID As String, ByVal incidentCode As String, ByVal application As String, ByVal description As String, ByVal amount As Decimal, ByVal data As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("SaveJournal", New Object() {customerID, journalDate, block_ID, transactionID, incidentCode, application, description, amount, data})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SaveJournalAsync(ByVal customerID As Integer, ByVal journalDate As Date, ByVal block_ID As String, ByVal transactionID As String, ByVal incidentCode As String, ByVal application As String, ByVal description As String, ByVal amount As Decimal, ByVal data As String)
            Me.SaveJournalAsync(customerID, journalDate, block_ID, transactionID, incidentCode, application, description, amount, data, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SaveJournalAsync(ByVal customerID As Integer, ByVal journalDate As Date, ByVal block_ID As String, ByVal transactionID As String, ByVal incidentCode As String, ByVal application As String, ByVal description As String, ByVal amount As Decimal, ByVal data As String, ByVal userState As Object)
            If (Me.SaveJournalOperationCompleted Is Nothing) Then
                Me.SaveJournalOperationCompleted = AddressOf Me.OnSaveJournalOperationCompleted
            End If
            Me.InvokeAsync("SaveJournal", New Object() {customerID, journalDate, block_ID, transactionID, incidentCode, application, description, amount, data}, Me.SaveJournalOperationCompleted, userState)
        End Sub
        
        Private Sub OnSaveJournalOperationCompleted(ByVal arg As Object)
            If (Not (Me.SaveJournalCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SaveJournalCompleted(Me, New SaveJournalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://fldevez.org/SaveJournalXML", RequestNamespace:="http://fldevez.org/", ResponseNamespace:="http://fldevez.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SaveJournalXML(ByVal customerID As Integer, ByVal journalDate As Date, ByVal block_ID As String, ByVal transactionID As String, ByVal IncidentCode As String, ByVal Application As String, ByVal Description As String, ByVal Amount As Decimal, ByVal data As String) As String
            Dim results() As Object = Me.Invoke("SaveJournalXML", New Object() {customerID, journalDate, block_ID, transactionID, IncidentCode, Application, Description, Amount, data})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SaveJournalXMLAsync(ByVal customerID As Integer, ByVal journalDate As Date, ByVal block_ID As String, ByVal transactionID As String, ByVal IncidentCode As String, ByVal Application As String, ByVal Description As String, ByVal Amount As Decimal, ByVal data As String)
            Me.SaveJournalXMLAsync(customerID, journalDate, block_ID, transactionID, IncidentCode, Application, Description, Amount, data, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SaveJournalXMLAsync(ByVal customerID As Integer, ByVal journalDate As Date, ByVal block_ID As String, ByVal transactionID As String, ByVal IncidentCode As String, ByVal Application As String, ByVal Description As String, ByVal Amount As Decimal, ByVal data As String, ByVal userState As Object)
            If (Me.SaveJournalXMLOperationCompleted Is Nothing) Then
                Me.SaveJournalXMLOperationCompleted = AddressOf Me.OnSaveJournalXMLOperationCompleted
            End If
            Me.InvokeAsync("SaveJournalXML", New Object() {customerID, journalDate, block_ID, transactionID, IncidentCode, Application, Description, Amount, data}, Me.SaveJournalXMLOperationCompleted, userState)
        End Sub
        
        Private Sub OnSaveJournalXMLOperationCompleted(ByVal arg As Object)
            If (Not (Me.SaveJournalXMLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SaveJournalXMLCompleted(Me, New SaveJournalXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub SaveJournalCompletedEventHandler(ByVal sender As Object, ByVal e As SaveJournalCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SaveJournalCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub SaveJournalXMLCompletedEventHandler(ByVal sender As Object, ByVal e As SaveJournalXMLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SaveJournalXMLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
